import { useState, useEffect } from 'react';
import { DOMAINS, domainName } from '../data/questions.js';
import { LEVELS, SPOT_ASSESSMENT_SIZE } from '../data/config.js';
import { scoreSpotTheError, scoreSpotTheErrorByDomain, scoreToLevel } from '../lib/scoring.js';
import { apiFetch } from '../lib/apiFetch.js';

// ─────────────────────────────────────────────────────────────────────────────
// SpotTheError — a scored QA-audit ASSESSMENT.
//
// The navigator is shown a set of flawed agent transcripts (each generated by
// Gemini with exactly one planted SOP violation). For each item they get ONE
// click to identify the message where the agent broke policy — click accuracy is
// the whole score. Scores feed the capability matrix (like the main check).
//
// Two modes, driven by props:
//   • mode='domain'  — deep single-domain assessment (SPOT_ASSESSMENT_SIZE items
//                      for one domain). Launched from the training plan; the
//                      parent merges the one domain score into the result doc.
//   • mode='full'    — full-profile assessment: one item per domain across all of
//                      `domains`. An alternative to the MCQ check; the parent
//                      saves a complete per-domain result.
//
// Flow:  loading → active (item-by-item, one click each) → review → saving → done
//
// onComplete(domainScores, mode) hands the parent a { domainId: percent } map.
// ─────────────────────────────────────────────────────────────────────────────

const GENERATE_TIMEOUT_MS = 25_000;

export default function SpotTheError({
  navigatorId, // eslint-disable-line no-unused-vars
  name,        // eslint-disable-line no-unused-vars
  domains,
  mode = 'domain',
  department = 'pediatrics',
  onBack,
  onFinish,
  onComplete,
}) {
  const [phase, setPhase] = useState('loading');
  // 'loading' | 'active' | 'review' | 'saving' | 'done'

  const [items,   setItems]   = useState([]);   // [{ domainId, transcript, errorIndex, modelExplanation }]
  const [current, setCurrent] = useState(0);    // index of the item being answered
  const [picks,   setPicks]   = useState([]);   // [{ picked:number, correct:boolean }] aligned to items
  const [genError, setGenError] = useState('');

  const finishTo = onFinish ?? onBack;
  const isFull = mode === 'full';
  const titleLabel = isFull ? 'the full assessment' : domainName(domains?.[0]);

  // Build the generation plan: which domain each item covers.
  // Full mode → one item per domain; domain mode → SPOT_ASSESSMENT_SIZE items.
  const plan = isFull
    ? (domains ?? [])
    : Array.from({ length: SPOT_ASSESSMENT_SIZE }, () => domains?.[0]);

  useEffect(() => {
    generate();
  }, []); // eslint-disable-line react-hooks/exhaustive-deps

  const generate = async () => {
    setPhase('loading');
    setGenError('');
    setItems([]);
    setPicks([]);
    setCurrent(0);
    try {
      // Fire the item generations in parallel; keep whatever succeeds so a single
      // rate-limited call doesn't sink the whole assessment.
      const results = await Promise.allSettled(
        plan.map((domainId) =>
          apiFetch('/api/generate-audit', { domain: domainId, department }, GENERATE_TIMEOUT_MS)
            .then((data) => ({ domainId, data }))
        )
      );
      const got = results
        .filter((r) => r.status === 'fulfilled' && Array.isArray(r.value?.data?.transcript))
        .map((r) => ({
          domainId: r.value.domainId,
          transcript: r.value.data.transcript,
          errorIndex: r.value.data.errorIndex,
          modelExplanation: r.value.data.modelExplanation,
        }));
      if (got.length === 0) {
        setGenError('Could not generate the assessment — check your connection and try again.');
        return;
      }
      setItems(got);
      setPhase('active');
    } catch (err) {
      setGenError(
        err?.name === 'AbortError'
          ? 'The request timed out — check your connection and try again.'
          : err?.message || 'Failed to generate the assessment.'
      );
    }
  };

  // One click per item = the answer. Records correctness, then locks the item.
  const answered = picks[current] !== undefined;

  const handleBubbleClick = (index) => {
    if (answered) return;
    const item = items[current];
    if (item?.transcript[index]?.speaker !== 'Agent') return; // only Agent turns are answerable
    const correct = index === item.errorIndex;
    setPicks((prev) => {
      const next = [...prev];
      next[current] = { picked: index, correct };
      return next;
    });
  };

  const advance = () => {
    if (current < items.length - 1) setCurrent((c) => c + 1);
    else setPhase('review');
  };

  const overallScore = scoreSpotTheError(picks);

  // Per-domain scores. In full mode, backfill any domain that failed to generate
  // an item with 0 so the saved profile is complete.
  const graded = items.map((it, i) => ({ domainId: it.domainId, correct: !!picks[i]?.correct }));
  const byDomain = scoreSpotTheErrorByDomain(graded);
  const domainScores = isFull
    ? Object.fromEntries((domains ?? []).map((d) => [d, byDomain[d] ?? 0]))
    : byDomain;

  const finish = async () => {
    setPhase('saving');
    try {
      await onComplete?.(domainScores, mode);
    } catch (err) {
      console.error('Failed to save assessment result:', err);
      // Non-blocking — the navigator still sees their score locally.
    }
    setPhase('done');
  };

  // ─────────────────────────────────────────────────────────────────────────────
  // Render
  // ─────────────────────────────────────────────────────────────────────────────

  // ── Loading / error ──────────────────────────────────────────────────────────

  if (phase === 'loading') {
    return (
      <section className="spot-error view-enter">
        <button className="linkbtn spot-error__back" onClick={onBack}>← Back</button>
        <div className="card spot-error__loading-card">
          {genError ? (
            <>
              <p className="gate__error">{genError}</p>
              <button className="btn btn--primary" onClick={generate}>Try again</button>
            </>
          ) : (
            <>
              <div className="skeleton skeleton--line" style={{ width: '70%', marginBottom: '0.75rem' }} />
              <div className="skeleton skeleton--line" style={{ width: '55%', marginBottom: '0.75rem' }} />
              <div className="skeleton skeleton--line" style={{ width: '80%', marginBottom: '0.75rem' }} />
              <div className="skeleton skeleton--line" style={{ width: '50%', marginBottom: '0.75rem' }} />
              <div className="skeleton skeleton--line" style={{ width: '65%' }} />
              <p className="spot-error__loading-label">Building {titleLabel}…</p>
            </>
          )}
        </div>
      </section>
    );
  }

  // ── Done ─────────────────────────────────────────────────────────────────────

  if (phase === 'done') {
    return (
      <section className="spot-error view-enter">
        <div className="card spot-error__done">
          <span className="spot-error__done-glyph" aria-hidden="true">✓</span>
          <h2 className="overview__panel-title">Assessment recorded</h2>
          <p className="readoff__sub">
            {isFull
              ? 'Your capability profile has been updated. You can view it on your dashboard.'
              : `Your ${domainName(domains?.[0])} score has been updated on your capability profile.`}{' '}
            You can retake this assessment any time.
          </p>
          <div className="spot-error__done-actions">
            <button className="btn btn--primary" onClick={finishTo}>
              {isFull ? 'See my results' : 'Back to my training'}
            </button>
            <button className="btn btn--ghost" onClick={generate}>Retake assessment</button>
          </div>
        </div>
      </section>
    );
  }

  // ── Review (final score + per-item breakdown) ─────────────────────────────────

  if (phase === 'review' || phase === 'saving') {
    const level = LEVELS[scoreToLevel(overallScore)];
    const correctCount = picks.filter((p) => p?.correct).length;
    return (
      <section className="spot-error view-enter">
        <div className="card spot-error__scorecard">
          <span className="tag tag--accent">{isFull ? 'Full assessment' : domainName(domains?.[0])}</span>
          <h1 className="spot-error__title">Assessment results</h1>
          <div className="spot-error__score" style={{ color: level.color }}>
            <span className="spot-error__score-value">{overallScore}%</span>
            <span className="spot-error__score-level" style={{ background: level.color, color: level.text }}>
              {level.label}
            </span>
          </div>
          <p className="readoff__sub">
            You correctly identified <strong>{correctCount} of {items.length}</strong> policy errors.
            This {isFull ? 'now sets your capability ratings.' : `now feeds your ${domainName(domains?.[0])} capability rating.`}
          </p>
        </div>

        {isFull && (
          <div className="card spot-error__domain-breakdown">
            <h2 className="overview__panel-title">By domain</h2>
            <ul className="spot-error__domain-list">
              {(domains ?? []).map((d) => {
                const pct = domainScores[d] ?? 0;
                const lvl = LEVELS[scoreToLevel(pct)];
                return (
                  <li key={d} className="spot-error__domain-row">
                    <span className="spot-error__domain-name">{domainName(d)}</span>
                    <span className="spot-error__domain-level" style={{ background: lvl.color, color: lvl.text }}>
                      {lvl.label}
                    </span>
                  </li>
                );
              })}
            </ul>
          </div>
        )}

        <ol className="spot-error__review-list">
          {items.map((item, i) => {
            const pick = picks[i];
            const ok = pick?.correct;
            return (
              <li key={i} className={`card spot-error__review-item spot-error__review-item--${ok ? 'ok' : 'miss'}`}>
                <div className="spot-error__review-head">
                  <span className="spot-error__review-num">
                    Item {i + 1} · {domainName(item.domainId)}
                  </span>
                  <span className={`spot-error__review-badge spot-error__review-badge--${ok ? 'ok' : 'miss'}`}>
                    {ok ? '✓ Correct' : '✗ Missed'}
                  </span>
                </div>
                <p className="spot-error__review-error">
                  <strong>The error:</strong>{' '}
                  “{item.transcript[item.errorIndex]?.message}”
                </p>
                <p className="spot-error__model-text">{item.modelExplanation}</p>
              </li>
            );
          })}
        </ol>

        <div className="spot-error__done-actions">
          <button className="btn btn--primary" onClick={finish} disabled={phase === 'saving'}>
            {phase === 'saving' ? 'Saving…' : 'Save & finish'}
          </button>
        </div>
      </section>
    );
  }

  // ── Active (one item at a time) ───────────────────────────────────────────────

  const item = items[current];
  const pick = picks[current];

  return (
    <section className="spot-error view-enter">
      <button className="linkbtn spot-error__back" onClick={onBack}>← Back</button>

      {/* Header card */}
      <div className="card spot-error__header">
        <div className="spot-error__header-left">
          <span className="tag tag--accent">{domainName(item.domainId)}</span>
          <h1 className="spot-error__title">Spot the Error — Assessment</h1>
          <p className="spot-error__instructions">
            The agent in this conversation made one critical policy mistake.{' '}
            <strong>Click the exact message where they went wrong.</strong> You get one attempt per item.
          </p>
        </div>
        <div className="spot-error__progress" role="status">
          Item {current + 1} of {items.length}
        </div>
      </div>

      {/* Transcript */}
      <div className="spot-error__transcript" role="list">
        {item.transcript.map((turn, i) => {
          const isAgent   = turn.speaker === 'Agent';
          const isError   = i === item.errorIndex;
          const clickable = !answered && isAgent;
          const isPicked  = pick?.picked === i;
          // Reveal the correct message + a wrong pick only after the item is answered.
          const revealCorrect = answered && isError;
          const revealWrong   = answered && isPicked && !pick.correct;

          const classes = [
            'spot-error__bubble',
            `spot-error__bubble--${isAgent ? 'agent' : 'patient'}`,
            clickable      ? 'spot-error__bubble--clickable' : '',
            revealCorrect  ? 'spot-error__bubble--found'     : '',
            revealWrong    ? 'spot-error__bubble--wrong'     : '',
          ].filter(Boolean).join(' ');

          return (
            <div key={i} className={classes} role="listitem">
              <span className="spot-error__speaker">{turn.speaker}</span>
              <button
                className="spot-error__message"
                onClick={() => handleBubbleClick(i)}
                disabled={!clickable}
                type="button"
                aria-label={clickable ? 'Select this message as the error' : undefined}
              >
                {turn.message}
              </button>
            </div>
          );
        })}
      </div>

      {/* Answer feedback + advance */}
      {answered && (
        <div className="card spot-error__feedback">
          <p className={`spot-error__feedback-verdict spot-error__feedback-verdict--${pick.correct ? 'ok' : 'miss'}`}>
            {pick.correct
              ? '✓ Correct — that message broke policy.'
              : '✗ Not quite — the highlighted message is where the agent went wrong.'}
          </p>
          <button className="btn btn--primary" onClick={advance} type="button">
            {current < items.length - 1 ? 'Next item →' : 'See results'}
          </button>
        </div>
      )}
    </section>
  );
}
